POST http://localhost:5000/api/auth/dang-nhap
Content-Type: application/json

{
  "email": "khoidz@gmail.com",
  "mat_khau": "123"
}

###
GET http://localhost:5000/api/auth/thong-tin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdiMjg0ZTBjLTI1YzAtNDYyMy04OGViLWU4ZDJjZjNkZTEwOSIsImVtYWlsIjoibmhhbnZpZW4xQGdtYWlsLmNvbSIsImxvYWkiOiJuaGFuX3ZpZW4iLCJuaGFuX3ZpZW5faWQiOiJmYzU4OGI0OC1kNDRjLTQ3M2ItYjI0Yy02OTRlOWZhMGNkOTYiLCJ2YWlfdHJvIjoibmhhbl92aWVuIiwia2hhY2hfaGFuZ19pZCI6bnVsbCwiaWF0IjoxNzc5MTc1OTcyLCJleHAiOjE3Nzk3ODA3NzJ9.ttvWY8CZVsfyLcUsJwbjY9E-BYtpt95gBd94bKW3BcY
