GET http://localhost:5000/api/danh-muc

###
GET http://localhost:5000/api/danh-muc/9e79dadb-4423-4338-bb5c-2873b54e4e27

###
POST http://localhost:5000/api/admin/danh-muc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZiMjgyYjY3LTY0MWItNDk3YS04MDgwLWI4ZjBiNzExYWU4OCIsImVtYWlsIjoicXVhbmx5MUBnbWFpbC5jb20iLCJsb2FpIjoibmhhbl92aWVuIiwibmhhbl92aWVuX2lkIjoiZmFkM2ZlYWEtYTczNC00NTIzLWI0MzgtZGIxNGMxM2NiZGJiIiwidmFpX3RybyI6InF1YW5fbHkiLCJraGFjaF9oYW5nX2lkIjpudWxsLCJpYXQiOjE3NzkzNjg1MTcsImV4cCI6MTc3OTk3MzMxN30.i85eQk4sI6ts5GGGMBP_FNm1NnC3gmeQIZCMjCqpGy0
Content-Type: application/json

{
  "ten": "Tranh chan dung"
}

###
PUT http://localhost:5000/api/admin/danh-muc/394fc025-2808-49bb-85ee-d95359ef3e68
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRmZGM5NWFhLWZhZjMtNDVlMS04NmMxLTUzZjZlMDVhMTVmNyIsImVtYWlsIjoibmhhbnZpZW4xQGdtYWlsLmNvbSIsImxvYWkiOiJuaGFuX3ZpZW4iLCJuaGFuX3ZpZW5faWQiOiJjZGExNmJkNS1lODg5LTRkYWMtYjVkOS1mYzRiNjIyOGI3ODgiLCJ2YWlfdHJvIjoiYmFuX2hhbmciLCJraGFjaF9oYW5nX2lkIjpudWxsLCJpYXQiOjE3NzkyMDM4NjAsImV4cCI6MTc3OTgwODY2MH0.0p408c_xfbuu6na3VZSXENOBYLOqv45x1ed00x89xcs
Content-Type: application/json

{
  "ten": "Tranh anime"
}

###
DELETE http://localhost:5000/api/admin/danh-muc/394fc025-2808-49bb-85ee-d95359ef3e68
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRmZGM5NWFhLWZhZjMtNDVlMS04NmMxLTUzZjZlMDVhMTVmNyIsImVtYWlsIjoibmhhbnZpZW4xQGdtYWlsLmNvbSIsImxvYWkiOiJuaGFuX3ZpZW4iLCJuaGFuX3ZpZW5faWQiOiJjZGExNmJkNS1lODg5LTRkYWMtYjVkOS1mYzRiNjIyOGI3ODgiLCJ2YWlfdHJvIjoiYmFuX2hhbmciLCJraGFjaF9oYW5nX2lkIjpudWxsLCJpYXQiOjE3NzkyMDM4NjAsImV4cCI6MTc3OTgwODY2MH0.0p408c_xfbuu6na3VZSXENOBYLOqv45x1ed00x89xcs
