GET http://localhost:5000/api/don-hang
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZiMjgyYjY3LTY0MWItNDk3YS04MDgwLWI4ZjBiNzExYWU4OCIsImVtYWlsIjoicXVhbmx5MUBnbWFpbC5jb20iLCJsb2FpIjoibmhhbl92aWVuIiwibmhhbl92aWVuX2lkIjoiZmFkM2ZlYWEtYTczNC00NTIzLWI0MzgtZGIxNGMxM2NiZGJiIiwidmFpX3RybyI6InF1YW5fbHkiLCJraGFjaF9oYW5nX2lkIjpudWxsLCJpYXQiOjE3Nzk0MDk1OTEsImV4cCI6MTc4MDAxNDM5MX0.hYOlnp0wg6bIPgmOMnJfLswkQewQCsRsog1UZs5QgZo

###
POST http://localhost:5000/api/don-hang/them
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQwYWFjYjcyLTlmMzEtNGExZi1iNjFmLWRjYjExNjZkODUzYiIsImVtYWlsIjoia2hhY2hoYW5nMUBnbWFpbC5jb20iLCJsb2FpIjoia2hhY2hfaGFuZyIsIm5oYW5fdmllbl9pZCI6bnVsbCwidmFpX3RybyI6bnVsbCwia2hhY2hfaGFuZ19pZCI6ImYyZmQxNWI2LWQ5ZWQtNDkwYi05YWY4LTM3Mjc4Mzc2ODNiYyIsImlhdCI6MTc3OTQ0MjM4MywiZXhwIjoxNzgwMDQ3MTgzfQ.RYuvFkGMPvRfAKBiVzw4W5DUjMyCuhNLra3pcM12YrE
Content-Type: application/json

{
  "dia_chi_giao": "123 Nguyễn Trãi, Q1, TP.HCM",
  "don_vi_van_chuyen_id": "7100e545-169d-4057-9e52-bb2a8a16a343",
  "ghi_chu": "Giao buổi sáng"
}