GET http://localhost:5000/api/gio-hang
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZiMjgyYjY3LTY0MWItNDk3YS04MDgwLWI4ZjBiNzExYWU4OCIsImVtYWlsIjoicXVhbmx5MUBnbWFpbC5jb20iLCJsb2FpIjoibmhhbl92aWVuIiwibmhhbl92aWVuX2lkIjoiZmFkM2ZlYWEtYTczNC00NTIzLWI0MzgtZGIxNGMxM2NiZGJiIiwidmFpX3RybyI6InF1YW5fbHkiLCJraGFjaF9oYW5nX2lkIjpudWxsLCJpYXQiOjE3NzkzNjg1MTcsImV4cCI6MTc3OTk3MzMxN30.i85eQk4sI6ts5GGGMBP_FNm1NnC3gmeQIZCMjCqpGy0

###
POST http://localhost:5000/api/gio-hang/them
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZiMjgyYjY3LTY0MWItNDk3YS04MDgwLWI4ZjBiNzExYWU4OCIsImVtYWlsIjoicXVhbmx5MUBnbWFpbC5jb20iLCJsb2FpIjoibmhhbl92aWVuIiwibmhhbl92aWVuX2lkIjoiZmFkM2ZlYWEtYTczNC00NTIzLWI0MzgtZGIxNGMxM2NiZGJiIiwidmFpX3RybyI6InF1YW5fbHkiLCJraGFjaF9oYW5nX2lkIjpudWxsLCJpYXQiOjE3NzkzNjg1MTcsImV4cCI6MTc3OTk3MzMxN30.i85eQk4sI6ts5GGGMBP_FNm1NnC3gmeQIZCMjCqpGy0
Content-Type: application/json

{
  "tranh_id": "531a96c4-470b-450d-971c-cde5bcedfdee",
  "so_luong": 2
}

###
PUT http://localhost:5000/api/gio-hang/05811c23-b98c-4314-85a0-5e0ef66b524d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZiMjgyYjY3LTY0MWItNDk3YS04MDgwLWI4ZjBiNzExYWU4OCIsImVtYWlsIjoicXVhbmx5MUBnbWFpbC5jb20iLCJsb2FpIjoibmhhbl92aWVuIiwibmhhbl92aWVuX2lkIjoiZmFkM2ZlYWEtYTczNC00NTIzLWI0MzgtZGIxNGMxM2NiZGJiIiwidmFpX3RybyI6InF1YW5fbHkiLCJraGFjaF9oYW5nX2lkIjpudWxsLCJpYXQiOjE3NzkzNjg1MTcsImV4cCI6MTc3OTk3MzMxN30.i85eQk4sI6ts5GGGMBP_FNm1NnC3gmeQIZCMjCqpGy0
Content-Type: application/json

{
  "so_luong": 8
}

###
DELETE http://localhost:5000/api/gio-hang/05811c23-b98c-4314-85a0-5e0ef66b524d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhmNTNmNzgzLWRjMTAtNDM4My1iYWFlLTcxNThjNWQ3NzVhMSIsImVtYWlsIjoia2hhY2hoYW5nMUBnbWFpbC5jb20iLCJsb2FpIjoia2hhY2hfaGFuZyIsIm5oYW5fdmllbl9pZCI6bnVsbCwidmFpX3RybyI6bnVsbCwia2hhY2hfaGFuZ19pZCI6IjlhZjkxMWQ4LWVlY2MtNDk5Yi1iYzhiLWMyY2NjOTFkMjBmYyIsImlhdCI6MTc3OTMzMzIzNSwiZXhwIjoxNzc5OTM4MDM1fQ.dLZKCTz4m55B9RxTcol_3tH0GinmdWPunOGR0-XoGO0
