GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Luan",
  "email": "luan@gmail.com",
  "mat_khau": "con cho mysql",
  "loai": "khach_hang"
}

