POST http://localhost:5000/api/nhan-vien/dang-ky
Content-Type: application/json

{
  "email": "banhang1@gmail.com",
  "mat_khau": "123456",
  "ho_ten": "Nguyen Van A",
  "ngay_sinh": "2000-05-20",
  "dia_chi": "TP.HCM",
  "sdt": "0911222333",
  "vai_tro": "ban_hang"
}
