GET http://localhost:5000/api/tac-gia

###
GET http://localhost:5000/api/tac-gia/394fc025-2808-49bb-85ee-d95359ef3e68

###
POST http://localhost:5000/api/admin/tac-gia
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZiMjgyYjY3LTY0MWItNDk3YS04MDgwLWI4ZjBiNzExYWU4OCIsImVtYWlsIjoicXVhbmx5MUBnbWFpbC5jb20iLCJsb2FpIjoibmhhbl92aWVuIiwibmhhbl92aWVuX2lkIjoiZmFkM2ZlYWEtYTczNC00NTIzLWI0MzgtZGIxNGMxM2NiZGJiIiwidmFpX3RybyI6InF1YW5fbHkiLCJraGFjaF9oYW5nX2lkIjpudWxsLCJpYXQiOjE3NzkzNjg1MTcsImV4cCI6MTc3OTk3MzMxN30.i85eQk4sI6ts5GGGMBP_FNm1NnC3gmeQIZCMjCqpGy0
Content-Type: application/json

{
  "ho_ten": "John Wrick",
  "ngay_sinh": "1995-06-20",
  "sdt": "0902483598",
  "dia_chi": "New York",
  "tieu_su": ""
}

###
PUT http://localhost:5000/api/admin/tac-gia/394fc025-2808-49bb-85ee-d95359ef3e68
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQwYWFjYjcyLTlmMzEtNGExZi1iNjFmLWRjYjExNjZkODUzYiIsImVtYWlsIjoia2hhY2hoYW5nMUBnbWFpbC5jb20iLCJsb2FpIjoia2hhY2hfaGFuZyIsIm5oYW5fdmllbl9pZCI6bnVsbCwidmFpX3RybyI6bnVsbCwia2hhY2hfaGFuZ19pZCI6ImYyZmQxNWI2LWQ5ZWQtNDkwYi05YWY4LTM3Mjc4Mzc2ODNiYyIsImlhdCI6MTc3OTM2ODQ5MywiZXhwIjoxNzc5OTczMjkzfQ.D0rsxkJChCxK4369fUBz7j8mz1MiFP0JaqIhQrWgS3M
Content-Type: application/json

{
  "ho_ten": "John Wrick",
  "ngay_sinh": "1995-06-20",
  "sdt": "0902483598",
  "dia_chi": "New York",
  "tieu_su": ""
}

###
DELETE http://localhost:5000/api/admin/tac-gia/394fc025-2808-49bb-85ee-d95359ef3e68
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRmZGM5NWFhLWZhZjMtNDVlMS04NmMxLTUzZjZlMDVhMTVmNyIsImVtYWlsIjoibmhhbnZpZW4xQGdtYWlsLmNvbSIsImxvYWkiOiJuaGFuX3ZpZW4iLCJuaGFuX3ZpZW5faWQiOiJjZGExNmJkNS1lODg5LTRkYWMtYjVkOS1mYzRiNjIyOGI3ODgiLCJ2YWlfdHJvIjoiYmFuX2hhbmciLCJraGFjaF9oYW5nX2lkIjpudWxsLCJpYXQiOjE3NzkyMDM4NjAsImV4cCI6MTc3OTgwODY2MH0.0p408c_xfbuu6na3VZSXENOBYLOqv45x1ed00x89xcs
