GET http://localhost:5000/api/tranh

###
GET http://localhost:5000/api/tranh/9adde2b1-0f2a-48d9-a5a4-f19d675d9dd6

###
POST http://localhost:5000/api/admin/tranh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZiMjgyYjY3LTY0MWItNDk3YS04MDgwLWI4ZjBiNzExYWU4OCIsImVtYWlsIjoicXVhbmx5MUBnbWFpbC5jb20iLCJsb2FpIjoibmhhbl92aWVuIiwibmhhbl92aWVuX2lkIjoiZmFkM2ZlYWEtYTczNC00NTIzLWI0MzgtZGIxNGMxM2NiZGJiIiwidmFpX3RybyI6InF1YW5fbHkiLCJraGFjaF9oYW5nX2lkIjpudWxsLCJpYXQiOjE3NzkzNjg1MTcsImV4cCI6MTc3OTk3MzMxN30.i85eQk4sI6ts5GGGMBP_FNm1NnC3gmeQIZCMjCqpGy0
Content-Type: application/json

{
  "tac_gia_id": "ba4abd5e-1a4b-4210-b9e7-048472afa284",
  "danh_muc_id": "7f19eb1e-00d4-4b91-bebd-44d9e78efa5d",  
  "kho_id": "id-kho-o-day",
  "ten_tranh": "Mona lisa 2",
  "mo_ta": "Tranh sen vẽ tay",
  "kich_thuoc": "60x80cm",
  "gia_ban": 2500000,
  "gia_von": 1200000,
  "so_luong_ton": 1,
  "trang_thai": "ban"
}

###
PUT http://localhost:5000/api/admin/tranh/9adde2b1-0f2a-48d9-a5a4-f19d675d9dd6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImExNjViMTMxLThkMWItNDNiYy1iOGFkLTA5NWFjZTEyNDkxYiIsImVtYWlsIjoicXVhbl9seTFAZ21haWwuY29tIiwibG9haSI6Im5oYW5fdmllbiIsIm5oYW5fdmllbl9pZCI6ImUyYjAyYjI3LTExOWYtNGRjNy1iNjliLTc0ZTExMTQzYjhmNyIsInZhaV90cm8iOiJxdWFuX2x5Iiwia2hhY2hfaGFuZ19pZCI6bnVsbCwiaWF0IjoxNzc5MjUxMjg0LCJleHAiOjE3Nzk4NTYwODR9.miRciUbDYZykJgszaXfe63JTD8DbFCgO3OAZZdfRTW0
Content-Type: application/json

{
  "tac_gia_id": "id-tac-gia-o-day",
  "danh_muc_id": "id-danh-muc-o-day",
  "kho_id": "id-kho-o-day",
  "ten_tranh": null,
  "mo_ta": "Tranh sen vẽ tay",
  "kich_thuoc": "60x80cm",
  "gia_ban": 2500000,
  "gia_von": 1200000,
  "so_luong_ton": 5,
  "trang_thai": "ban"
}

###
DELETE http://localhost:5000/api/admin/tranh/9adde2b1-0f2a-48d9-a5a4-f19d675d9dd6